version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    expose:
      - 5000
    command: uwsgi --http :5000 --module app:server --uid nobody --master
    image: barrymoo/crc-status-donut
    env_file:
      - .env
